import { guidedPracticeMediaByPracticeId } from './guidedPracticeMediaMap';
export const PRACTICE_CATEGORY_ORDER = [
  'Quick Practices',
  'Self-Connection',
  'Inner Child Work',
  'Parts Work',
  'Breathing Exercises',
];


const makeSteps = (steps) => steps.map((text, index) => ({
  id: `step-${index + 1}`,
  text,
  time: index * 45,
  duration: 45,
}));

const baseGuidedPracticeLibrary = [
  {
    id: 'quick-self-connection',
    title: 'Quick Self-Connection',
    description: 'A brief centering practice to notice what is present and return to Self-energy.',
    category: 'Quick Practices',
    level: 'Beginner',
    duration: '5 min',
    durationSeconds: 300,
    type: 'practice',
    route: '/meditation/quick-self-connection',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    steps: makeSteps([
      'Place both feet on the floor or notice the support beneath you. Take one slow breath.',
      'Ask inside: which part of me is most present right now?',
      'Notice that part with curiosity. You do not need to change it or make it go away.',
      'Invite a little more space around the part. See if calm, compassion, or clarity is available.',
      'Thank the part for showing up and choose one kind next step for the next few minutes.',
    ]),
  },
  {
    id: 'box-breathing-quick',
    title: 'Box Breathing',
    description: 'A quick 4-4-4-4 breath cycle for grounding and nervous system regulation.',
    category: 'Quick Practices',
    level: 'Beginner',
    duration: '4 min',
    durationSeconds: 240,
    type: 'breathing',
    route: '/meditation/box-breathing-quick',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    breathingPattern: [
      { label: 'Inhale', seconds: 4 },
      { label: 'Hold', seconds: 4 },
      { label: 'Exhale', seconds: 4 },
      { label: 'Hold', seconds: 4 },
    ],
    steps: makeSteps([
      'Inhale through your nose for 4 counts.',
      'Hold gently for 4 counts without straining.',
      'Exhale slowly for 4 counts.',
      'Hold softly for 4 counts, then repeat the box.',
    ]),
  },
  {
    id: 'inner-child-check-in',
    title: 'Inner Child Check-in',
    description: 'A short, gentle connection with a younger part that may need care today.',
    category: 'Quick Practices',
    level: 'Beginner',
    duration: '5 min',
    durationSeconds: 300,
    type: 'interactive',
    route: '/meditation/inner-child-check-in',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'What did your inner child want you to know, and what kind response can you offer?',
    steps: makeSteps([
      'Imagine sitting somewhere safe and comfortable with enough space for a younger part to appear.',
      'Invite your inner child to show up only as much as feels safe today.',
      'Notice their age, posture, expression, or feeling without forcing details.',
      'Ask gently: what do you need from me right now?',
      'Offer one sentence of reassurance, then write anything important in the reflection space below.',
    ]),
  },
  {
    id: 'meeting-your-self',
    title: 'Meeting Your Self',
    description: 'A guided meditation to connect with your core Self-energy.',
    category: 'Self-Connection',
    level: 'Beginner',
    duration: '15 min',
    durationSeconds: 900,
    type: 'meditation',
    route: '/meditation/meeting-your-self',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    steps: makeSteps([
      'Find a comfortable position and let your breath become easy.',
      'Notice any parts that are active and ask if they can give you a little space.',
      'Bring attention to a place in or around your body that feels calm or steady.',
      'Sense the qualities of Self-energy: calm, curiosity, compassion, clarity, courage, creativity, confidence, and connection.',
      'Rest in that presence and let your system know Self is here.',
    ]),
  },
  {
    id: 'cultivating-self-qualities',
    title: 'Cultivating Self Qualities',
    description: "Practice embodying the 8 C's of Self with gentle reflection and body awareness.",
    category: 'Self-Connection',
    level: 'Intermediate',
    duration: '20 min',
    durationSeconds: 1200,
    type: 'practice',
    route: '/meditation/cultivating-self-qualities',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'Which Self quality felt most available today, and where did you feel it?',
    steps: makeSteps([
      'Name the Self quality you would most like to invite today.',
      'Notice where that quality already exists, even faintly, in your body or breath.',
      'Ask any skeptical or protective parts what they need in order to allow more of this quality.',
      'Let the quality expand slowly, without pushing any part aside.',
      'Write one way you can practice this quality in daily life today.',
    ]),
  },
  {
    id: 'meeting-your-inner-child',
    title: 'Meeting Your Inner Child',
    description: 'Safely meet and connect with an inner child part from Self-energy.',
    category: 'Inner Child Work',
    level: 'Beginner',
    duration: '18 min',
    durationSeconds: 1080,
    type: 'meditation',
    route: '/meditation/meeting-your-inner-child',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    steps: makeSteps([
      'Create an inner safe place with enough comfort and choice for you and any younger part.',
      'Invite your inner child to appear at a distance that feels safe.',
      'Notice what they want you to understand before asking any deeper questions.',
      'Offer warmth, patience, and reassurance from your adult Self.',
      'Close by letting the child know when and how you will check in again.',
    ]),
  },
  {
    id: 'reparenting-meditation',
    title: 'Reparenting Meditation',
    description: 'Practice offering your inner child the care, protection, and attunement they needed.',
    category: 'Inner Child Work',
    level: 'Intermediate',
    duration: '25 min',
    durationSeconds: 1500,
    type: 'practice',
    route: '/meditation/reparenting-meditation',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'What words of care or protection did your younger part need to hear?',
    steps: makeSteps([
      'Invite the younger part to show you what kind of care was missing.',
      'Notice whether protectors need reassurance before you move closer.',
      'Offer one clear message: I am here, I believe you, and you are not alone.',
      'Ask what protection, comfort, or play this part wants now.',
      'Write a short reparenting note you can return to later.',
    ]),
  },
  {
    id: 'inner-child-play',
    title: 'Inner Child Play',
    description: "A playful exercise to reconnect with your inner child's joy, creativity, and spontaneity.",
    category: 'Inner Child Work',
    level: 'Beginner',
    duration: '12 min',
    durationSeconds: 720,
    type: 'interactive',
    route: '/meditation/inner-child-play',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'What kind of simple play or delight would your inner child enjoy this week?',
    steps: makeSteps([
      'Remember one activity, color, sound, or place that brought joy when you were young.',
      'Ask your inner child what feels playful rather than performative.',
      'Let yourself imagine a tiny version of that play for today.',
      'Notice protectors that feel embarrassed or busy and thank them for trying to help.',
      'Choose one realistic playful action and write it below.',
    ]),
  },
  {
    id: 'unblending-practice',
    title: 'Unblending Practice',
    description: "Learn to separate from parts when you're blended so Self can lead.",
    category: 'Parts Work',
    level: 'Intermediate',
    duration: '15 min',
    durationSeconds: 900,
    type: 'technique',
    route: '/meditation/unblending-practice',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'What changed when you shifted from being the feeling to noticing a part with the feeling?',
    steps: makeSteps([
      'Name the blended experience as gently as possible: a part of me feels this.',
      'Notice where the part is in or around your body.',
      'Ask the part if it can separate just a little so you can understand it better.',
      'Check for Self qualities that become more available with even a little space.',
      'Thank the part and note what it wants you to know.',
    ]),
  },
  {
    id: 'parts-council-meditation',
    title: 'Parts Council Meditation',
    description: 'Facilitate a respectful inner meeting where parts can speak and Self can listen.',
    category: 'Parts Work',
    level: 'Advanced',
    duration: '30 min',
    durationSeconds: 1800,
    type: 'meditation',
    route: '/meditation/parts-council-meditation',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'Which parts attended the council, and what did each most want understood?',
    steps: makeSteps([
      'Imagine a council room, circle, table, or landscape where all parts can have appropriate space.',
      'Invite only the parts that are willing and safe enough to participate today.',
      'Let each part speak briefly while Self listens without debate.',
      'Reflect common needs, fears, or hopes you hear in the system.',
      'Close by thanking every part and naming one next step that honors the whole system.',
    ]),
  },
  {
    id: 'working-with-firefighters',
    title: 'Working with Firefighters',
    description: 'Build understanding with impulsive or urgent protector parts without shaming them.',
    category: 'Parts Work',
    level: 'Intermediate',
    duration: '20 min',
    durationSeconds: 1200,
    type: 'technique',
    route: '/meditation/working-with-firefighters',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    reflectionPrompt: 'What is the firefighter trying to prevent or protect you from feeling?',
    steps: makeSteps([
      'Think of a firefighter response as a protector trying to reduce pain quickly.',
      'Thank the firefighter for trying to help, without approving harmful behavior.',
      'Ask what it fears would happen if it did not jump in.',
      'Ask what support it would need to pause for one breath before acting.',
      'Write one safer option this part may be willing to try next time.',
    ]),
  },
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    description: 'Calm your nervous system with a steady 4-4-4-4 breathing pattern.',
    category: 'Breathing Exercises',
    level: 'Beginner',
    duration: '10 min',
    durationSeconds: 600,
    type: 'breathing',
    route: '/meditation/box-breathing',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    breathingPattern: [
      { label: 'Inhale', seconds: 4 },
      { label: 'Hold', seconds: 4 },
      { label: 'Exhale', seconds: 4 },
      { label: 'Hold', seconds: 4 },
    ],
    steps: makeSteps([
      'Inhale for 4 counts.',
      'Hold for 4 counts.',
      'Exhale for 4 counts.',
      'Hold for 4 counts and begin again.',
    ]),
  },
  {
    id: '4-7-8-breathing',
    title: '4-7-8 Breathing',
    description: 'A relaxing breath sequence: inhale for 4, hold for 7, exhale for 8.',
    category: 'Breathing Exercises',
    level: 'Intermediate',
    duration: '12 min',
    durationSeconds: 720,
    type: 'breathing',
    route: '/meditation/4-7-8-breathing',
    audioUrl: null,
    coverImageUrl: null,
    uploadThingFileKey: null,
    fallbackPractice: true,
    breathingPattern: [
      { label: 'Inhale', seconds: 4 },
      { label: 'Hold', seconds: 7 },
      { label: 'Exhale', seconds: 8 },
    ],
    steps: makeSteps([
      'Inhale quietly for 4 counts.',
      'Hold the breath gently for 7 counts.',
      'Exhale slowly for 8 counts.',
      'Let the next inhale arrive naturally and repeat.',
    ]),
  },
];

export const guidedPracticeLibrary = baseGuidedPracticeLibrary.map((practice) => ({
  ...practice,
  ...(guidedPracticeMediaByPracticeId[practice.id] || {})
}));

export const guidedPracticeById = guidedPracticeLibrary.reduce((acc, practice) => {
  acc[practice.id] = practice;
  return acc;
}, {});

export const quickPractices = guidedPracticeLibrary.filter((practice) => practice.category === 'Quick Practices');

export const practiceCategories = PRACTICE_CATEGORY_ORDER.filter((category) => category !== 'Quick Practices').map((category) => ({
  name: category,
  practices: guidedPracticeLibrary.filter((practice) => practice.category === category),
}));

export function getGuidedPracticeById(practiceId) {
  return guidedPracticeById[practiceId] || null;
}
