export const guidedPracticeMediaMap = [
  {
    section: 'Q',
    itemNumber: 'Q1',
    practiceId: 'quick-self-connection',
    title: 'Quick Self-Connection',
    mp3Filename: 'quick-self-connection.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPHfRQByRTEMuS6oK8TlsLq9YemgGCtvHOj4Rp',
    uploadThingFileKey: 'TQXmWDkNFrzPHfRQByRTEMuS6oK8TlsLq9YemgGCtvHOj4Rp',
    expectedDuration: '5 min',
    appArea: 'meditation'
  },
  {
    section: 'Q',
    itemNumber: 'Q2',
    practiceId: 'box-breathing-quick',
    title: 'Box Breathing',
    mp3Filename: 'box-breathing-quick.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPWMhaGj3oPR4oig2prsFVNS6WjtubOl8U9xdI',
    uploadThingFileKey: 'TQXmWDkNFrzPWMhaGj3oPR4oig2prsFVNS6WjtubOl8U9xdI',
    expectedDuration: '4 min',
    appArea: 'meditation'
  },
  {
    section: 'Q',
    itemNumber: 'Q3',
    practiceId: 'inner-child-check-in',
    title: 'Inner Child Check-in',
    mp3Filename: 'inner-child-check-in.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPnYYHUxILBIHyFQVN7CDaEARXes6T5m9qZ1GY',
    uploadThingFileKey: 'TQXmWDkNFrzPnYYHUxILBIHyFQVN7CDaEARXes6T5m9qZ1GY',
    expectedDuration: '5 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A1',
    practiceId: 'meeting-your-self',
    title: 'Meeting Your Self',
    mp3Filename: '01_Meeting_Your_Self.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPLNLwZdST7ropz85CJOB0jAGgfxyU2EN1dcuL',
    uploadThingFileKey: 'TQXmWDkNFrzPLNLwZdST7ropz85CJOB0jAGgfxyU2EN1dcuL',
    captionsPath: '/meditations/captions/01_Meeting_Your_Self.srt',
    transcriptPath: '/meditations/transcripts/01_Meeting_Your_Self.txt',
    karaokePath: '/meditations/karaoke/01_Meeting_Your_Self.json',
    expectedDuration: '15 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A2',
    practiceId: 'cultivating-self-qualities',
    title: 'Cultivating Self Qualities',
    mp3Filename: '02_Cultivating_Self_Qualities.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPsJr5IXc3jOgpFdoSLski5Tb8DQM4AtCG1fmP',
    uploadThingFileKey: 'TQXmWDkNFrzPsJr5IXc3jOgpFdoSLski5Tb8DQM4AtCG1fmP',
    captionsPath: '/meditations/captions/02_Cultivating_Self_Qualities.srt',
    transcriptPath: '/meditations/transcripts/02_Cultivating_Self_Qualities.txt',
    karaokePath: '/meditations/karaoke/02_Cultivating_Self_Qualities.json',
    expectedDuration: '20 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A3',
    practiceId: 'meeting-your-inner-child',
    title: 'Meeting Your Inner Child',
    mp3Filename: '03_Meeting_Your_Inner_Child.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzP1TfpfeGNlxtGq3H4FdAhaKyXi8YVrn6WQs7j',
    uploadThingFileKey: 'TQXmWDkNFrzP1TfpfeGNlxtGq3H4FdAhaKyXi8YVrn6WQs7j',
    captionsPath: '/meditations/captions/03_Meeting_Your_Inner_Child.srt',
    transcriptPath: '/meditations/transcripts/03_Meeting_Your_Inner_Child.txt',
    karaokePath: '/meditations/karaoke/03_Meeting_Your_Inner_Child.json',
    expectedDuration: '18 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A4',
    practiceId: 'reparenting-meditation',
    title: 'Reparenting Meditation',
    mp3Filename: '04_Reparenting_Meditation.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPdmtax4Ex24wtubKUSVp7ZDEmvqAlPGjfTiNk',
    uploadThingFileKey: 'TQXmWDkNFrzPdmtax4Ex24wtubKUSVp7ZDEmvqAlPGjfTiNk',
    captionsPath: '/meditations/captions/04_Reparenting_Meditation.srt',
    transcriptPath: '/meditations/transcripts/04_Reparenting_Meditation.txt',
    karaokePath: '/meditations/karaoke/04_Reparenting_Meditation.json',
    expectedDuration: '25 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A5',
    practiceId: 'inner-child-play',
    title: 'Inner Child Play',
    mp3Filename: '05_Inner_Child_Play.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzP5TrOcZqZgazPFlLRNVCBrH37ATdxj6nYSIpb',
    uploadThingFileKey: 'TQXmWDkNFrzP5TrOcZqZgazPFlLRNVCBrH37ATdxj6nYSIpb',
    captionsPath: '/meditations/captions/05_Inner_Child_Play.srt',
    transcriptPath: '/meditations/transcripts/05_Inner_Child_Play.txt',
    karaokePath: '/meditations/karaoke/05_Inner_Child_Play.json',
    expectedDuration: '12 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A6',
    practiceId: 'unblending-practice',
    title: 'Unblending Practice',
    mp3Filename: '06_Unblending_Practice.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPchO2IrQwrzMC4j5USyFJRIA16m72xLsiOufd',
    uploadThingFileKey: 'TQXmWDkNFrzPchO2IrQwrzMC4j5USyFJRIA16m72xLsiOufd',
    captionsPath: '/meditations/captions/06_Unblending_Practice.srt',
    transcriptPath: '/meditations/transcripts/06_Unblending_Practice.txt',
    karaokePath: '/meditations/karaoke/06_Unblending_Practice.json',
    expectedDuration: '15 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A7',
    practiceId: 'parts-council-meditation',
    title: 'Parts Council Meditation',
    mp3Filename: '07_Parts_Council_Meditation.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPkx7joFfDy54uzKrPcMht0fboT3OI6La12Sgv',
    uploadThingFileKey: 'TQXmWDkNFrzPkx7joFfDy54uzKrPcMht0fboT3OI6La12Sgv',
    captionsPath: '/meditations/captions/07_Parts_Council_Meditation.srt',
    transcriptPath: '/meditations/transcripts/07_Parts_Council_Meditation.txt',
    karaokePath: '/meditations/karaoke/07_Parts_Council_Meditation.json',
    expectedDuration: '30 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A8',
    practiceId: 'working-with-firefighters',
    title: 'Working with Firefighters',
    mp3Filename: '08_Working_with_Firefighters.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPk9bYWEfDy54uzKrPcMht0fboT3OI6La12Sgv',
    uploadThingFileKey: 'TQXmWDkNFrzPk9bYWEfDy54uzKrPcMht0fboT3OI6La12Sgv',
    captionsPath: '/meditations/captions/08_Working_with_Firefighters.srt',
    transcriptPath: '/meditations/transcripts/08_Working_with_Firefighters.txt',
    karaokePath: '/meditations/karaoke/08_Working_with_Firefighters.json',
    expectedDuration: '20 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A9',
    practiceId: 'box-breathing',
    title: 'Box Breathing',
    mp3Filename: '09_Box_Breathing.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPxmoP39rfDF3UhWpk5QvKomN1CazR0MIdsgBZ',
    uploadThingFileKey: 'TQXmWDkNFrzPxmoP39rfDF3UhWpk5QvKomN1CazR0MIdsgBZ',
    captionsPath: '/meditations/captions/09_Box_Breathing.srt',
    transcriptPath: '/meditations/transcripts/09_Box_Breathing.txt',
    karaokePath: '/meditations/karaoke/09_Box_Breathing.json',
    expectedDuration: '10 min',
    appArea: 'meditation'
  },
  {
    section: 'A',
    itemNumber: 'A10',
    practiceId: '4-7-8-breathing',
    title: '4-7-8 Breathing',
    mp3Filename: '10_4-7-8_Breathing.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPnKN0iFILBIHyFQVN7CDaEARXes6T5m9qZ1GY',
    uploadThingFileKey: 'TQXmWDkNFrzPnKN0iFILBIHyFQVN7CDaEARXes6T5m9qZ1GY',
    captionsPath: '/meditations/captions/10_4-7-8_Breathing.srt',
    transcriptPath: '/meditations/transcripts/10_4-7-8_Breathing.txt',
    karaokePath: '/meditations/karaoke/10_4-7-8_Breathing.json',
    expectedDuration: '12 min',
    appArea: 'meditation'
  },
  {
    section: 'B',
    itemNumber: 'B1',
    practiceId: 'cultivating-self-energy-practice',
    title: 'Cultivating Self Energy Practice',
    mp3Filename: '11_Cultivating_Self_Energy_Practice.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPHlYllZTEMuS6oK8TlsLq9YemgGCtvHOj4Rpc',
    uploadThingFileKey: 'TQXmWDkNFrzPHlYllZTEMuS6oK8TlsLq9YemgGCtvHOj4Rpc',
    captionsPath: '/meditations/captions/11_Cultivating_Self_Energy_Practice.srt',
    transcriptPath: '/meditations/transcripts/11_Cultivating_Self_Energy_Practice.txt',
    karaokePath: '/meditations/karaoke/11_Cultivating_Self_Energy_Practice.json',
    expectedDuration: '18 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B2',
    practiceId: 'self-leadership-mastery-practice',
    title: 'Self Leadership Practice',
    mp3Filename: '12_Self_Leadership_Mastery_Practice.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPBIK46N7lGoOyb2sBNjLDnXMZpHYfKzvJRqcV',
    uploadThingFileKey: 'TQXmWDkNFrzPBIK46N7lGoOyb2sBNjLDnXMZpHYfKzvJRqcV',
    captionsPath: '/meditations/captions/12_Self_Leadership_Mastery_Practice.srt',
    transcriptPath: '/meditations/transcripts/12_Self_Leadership_Mastery_Practice.txt',
    karaokePath: '/meditations/karaoke/12_Self_Leadership_Mastery_Practice.json',
    expectedDuration: '20 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B3',
    practiceId: 'safe-place-visualization-inner-child',
    title: 'Safe Place Visualization for Your Inner Child',
    mp3Filename: '13_Safe_Place_Visualization_for_Your_Inner_Child.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPC44QWlguzpqQKxw9XNbMWJs08yIDto4FAcfR',
    uploadThingFileKey: 'TQXmWDkNFrzPC44QWlguzpqQKxw9XNbMWJs08yIDto4FAcfR',
    captionsPath: '/meditations/captions/13_Safe_Place_Visualization_for_Your_Inner_Child.srt',
    transcriptPath: '/meditations/transcripts/13_Safe_Place_Visualization_for_Your_Inner_Child.txt',
    karaokePath: '/meditations/karaoke/13_Safe_Place_Visualization_for_Your_Inner_Child.json',
    expectedDuration: '22 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B4',
    practiceId: 'body-based-inner-child-connection',
    title: 'Body-Based Inner Child Connection',
    mp3Filename: '14_Body-Based_Inner_Child_Connection.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPReQcCV24euXIWPSrF2xmyoascAjZvOLVGbDp',
    uploadThingFileKey: 'TQXmWDkNFrzPReQcCV24euXIWPSrF2xmyoascAjZvOLVGbDp',
    captionsPath: '/meditations/captions/14_Body-Based_Inner_Child_Connection.srt',
    transcriptPath: '/meditations/transcripts/14_Body-Based_Inner_Child_Connection.txt',
    karaokePath: '/meditations/karaoke/14_Body-Based_Inner_Child_Connection.json',
    expectedDuration: '22 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B5',
    practiceId: 'unburdening-ceremony',
    title: 'The Unburdening Ceremony',
    mp3Filename: '15_The_Unburdening_Ceremony.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzP40imPQKkD6aiKW3nXLloc0pbGeCdJVNv9hqQ',
    uploadThingFileKey: 'TQXmWDkNFrzP40imPQKkD6aiKW3nXLloc0pbGeCdJVNv9hqQ',
    captionsPath: '/meditations/captions/15_The_Unburdening_Ceremony.srt',
    transcriptPath: '/meditations/transcripts/15_The_Unburdening_Ceremony.txt',
    karaokePath: '/meditations/karaoke/15_The_Unburdening_Ceremony.json',
    expectedDuration: '25 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B6',
    practiceId: 'six-fs-protocol-mastery-practice',
    title: "6 F's Protocol Mastery Practice",
    mp3Filename: '16_6_Fs_Protocol_Mastery_Practice.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPKhFiRXx8Ynm7HtA0syVr31o5BDSixGLjXhIu',
    uploadThingFileKey: 'TQXmWDkNFrzPKhFiRXx8Ynm7HtA0syVr31o5BDSixGLjXhIu',
    captionsPath: '/meditations/captions/16_6_Fs_Protocol_Mastery_Practice.srt',
    transcriptPath: '/meditations/transcripts/16_6_Fs_Protocol_Mastery_Practice.txt',
    karaokePath: '/meditations/karaoke/16_6_Fs_Protocol_Mastery_Practice.json',
    expectedDuration: '18 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B7',
    practiceId: 'personalized-wound-healing-action-plan',
    title: 'Personalized Wound Healing Action Plan',
    mp3Filename: '17_Personalized_Wound_Healing_Action_Plan.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPeSM0EIaBVTGMq91vwQF7huSyoLzYJ2ZHRa8W',
    uploadThingFileKey: 'TQXmWDkNFrzPeSM0EIaBVTGMq91vwQF7huSyoLzYJ2ZHRa8W',
    captionsPath: '/meditations/captions/17_Personalized_Wound_Healing_Action_Plan.srt',
    transcriptPath: '/meditations/transcripts/17_Personalized_Wound_Healing_Action_Plan.txt',
    karaokePath: '/meditations/karaoke/17_Personalized_Wound_Healing_Action_Plan.json',
    expectedDuration: '20 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B8',
    practiceId: 'reparenting-your-inner-child',
    title: 'Reparenting Your Inner Child',
    mp3Filename: '18_Reparenting_Your_Inner_Child.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPpPxuXYtQi4yvEAWeGTPCdBYfVhoaR8l0Z925',
    uploadThingFileKey: 'TQXmWDkNFrzPpPxuXYtQi4yvEAWeGTPCdBYfVhoaR8l0Z925',
    captionsPath: '/meditations/captions/18_Reparenting_Your_Inner_Child.srt',
    transcriptPath: '/meditations/transcripts/18_Reparenting_Your_Inner_Child.txt',
    karaokePath: '/meditations/karaoke/18_Reparenting_Your_Inner_Child.json',
    expectedDuration: '15 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B9',
    practiceId: 'somatic-healing-body-scan',
    title: 'Somatic Healing Body Scan',
    mp3Filename: '19_Somatic_Healing_Body_Scan.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPJfpuJabRED1NHFY7QxnhS80VcaAqUm45TXtr',
    uploadThingFileKey: 'TQXmWDkNFrzPJfpuJabRED1NHFY7QxnhS80VcaAqUm45TXtr',
    captionsPath: '/meditations/captions/19_Somatic_Healing_Body_Scan.srt',
    transcriptPath: '/meditations/transcripts/19_Somatic_Healing_Body_Scan.txt',
    karaokePath: '/meditations/karaoke/19_Somatic_Healing_Body_Scan.json',
    expectedDuration: '18 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B10',
    practiceId: 'attachment-pattern-reflection',
    title: 'Attachment Pattern Reflection',
    mp3Filename: '20_Attachment_Pattern_Reflection.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPn1gMmJILBIHyFQVN7CDaEARXes6T5m9qZ1GY',
    uploadThingFileKey: 'TQXmWDkNFrzPn1gMmJILBIHyFQVN7CDaEARXes6T5m9qZ1GY',
    captionsPath: '/meditations/captions/20_Attachment_Pattern_Reflection.srt',
    transcriptPath: '/meditations/transcripts/20_Attachment_Pattern_Reflection.txt',
    karaokePath: '/meditations/karaoke/20_Attachment_Pattern_Reflection.json',
    expectedDuration: '15 min',
    appArea: 'curriculum'
  },
  {
    section: 'B',
    itemNumber: 'B11',
    practiceId: 'befriending-your-inner-critic',
    title: 'Befriending Your Inner Critic',
    mp3Filename: '21_Befriending_Your_Inner_Critic.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPW9vTqIoPR4oig2prsFVNS6WjtubOl8U9xdIG',
    uploadThingFileKey: 'TQXmWDkNFrzPW9vTqIoPR4oig2prsFVNS6WjtubOl8U9xdIG',
    captionsPath: '/meditations/captions/21_Befriending_Your_Inner_Critic.srt',
    transcriptPath: '/meditations/transcripts/21_Befriending_Your_Inner_Critic.txt',
    karaokePath: '/meditations/karaoke/21_Befriending_Your_Inner_Critic.json',
    expectedDuration: '18 min',
    appArea: 'curriculum'
  },
  {
    section: 'C',
    itemNumber: 'C1',
    practiceId: 'breath-anchor',
    title: 'Breath Anchor',
    mp3Filename: '22_Breath_Anchor.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPhzqlpiRRTb8uHd3LF7MyfxiGpczNqs5JkDnY',
    uploadThingFileKey: 'TQXmWDkNFrzPhzqlpiRRTb8uHd3LF7MyfxiGpczNqs5JkDnY',
    captionsPath: '/meditations/captions/22_Breath_Anchor.srt',
    transcriptPath: '/meditations/transcripts/22_Breath_Anchor.txt',
    karaokePath: '/meditations/karaoke/22_Breath_Anchor.json',
    expectedDuration: '2 min',
    appArea: 'micro-learning'
  },
  {
    section: 'C',
    itemNumber: 'C2',
    practiceId: 'self-compassion-pause',
    title: 'Self-Compassion Pause',
    mp3Filename: '23_Self-Compassion_Pause.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPhpFOP3RRTb8uHd3LF7MyfxiGpczNqs5JkDnY',
    uploadThingFileKey: 'TQXmWDkNFrzPhpFOP3RRTb8uHd3LF7MyfxiGpczNqs5JkDnY',
    captionsPath: '/meditations/captions/23_Self-Compassion_Pause.srt',
    transcriptPath: '/meditations/transcripts/23_Self-Compassion_Pause.txt',
    karaokePath: '/meditations/karaoke/23_Self-Compassion_Pause.json',
    expectedDuration: '2 min',
    appArea: 'micro-learning'
  },
  {
    section: 'C',
    itemNumber: 'C3',
    practiceId: 'quick-parts-check-in',
    title: 'Quick Parts Check-In',
    mp3Filename: '24_Quick_Parts_Check-In.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPWrhdgmoPR4oig2prsFVNS6WjtubOl8U9xdIG',
    uploadThingFileKey: 'TQXmWDkNFrzPWrhdgmoPR4oig2prsFVNS6WjtubOl8U9xdIG',
    captionsPath: '/meditations/captions/24_Quick_Parts_Check-In.srt',
    transcriptPath: '/meditations/transcripts/24_Quick_Parts_Check-In.txt',
    karaokePath: '/meditations/karaoke/24_Quick_Parts_Check-In.json',
    expectedDuration: '2 min',
    appArea: 'micro-learning'
  },
  {
    section: 'C',
    itemNumber: 'C4',
    practiceId: 'morning-intention',
    title: 'Morning Intention',
    mp3Filename: '25_Morning_Intention.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPQaO9CvMipn0hi7WrER2o5JbmxuqzjcCkZQlG',
    uploadThingFileKey: 'TQXmWDkNFrzPQaO9CvMipn0hi7WrER2o5JbmxuqzjcCkZQlG',
    captionsPath: '/meditations/captions/25_Morning_Intention.srt',
    transcriptPath: '/meditations/transcripts/25_Morning_Intention.txt',
    karaokePath: '/meditations/karaoke/25_Morning_Intention.json',
    expectedDuration: '2 min',
    appArea: 'micro-learning'
  },
  {
    section: 'C',
    itemNumber: 'C5',
    practiceId: 'evening-release',
    title: 'Evening Release',
    mp3Filename: '26_Evening_Release.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPfBclLvVz54V0hyU8pZlrDePq3gji9HMa2GEv',
    uploadThingFileKey: 'TQXmWDkNFrzPfBclLvVz54V0hyU8pZlrDePq3gji9HMa2GEv',
    captionsPath: '/meditations/captions/26_Evening_Release.srt',
    transcriptPath: '/meditations/transcripts/26_Evening_Release.txt',
    karaokePath: '/meditations/karaoke/26_Evening_Release.json',
    expectedDuration: '2 min',
    appArea: 'micro-learning'
  },
  {
    section: 'C',
    itemNumber: 'C6',
    practiceId: 'mini-body-scan',
    title: 'Mini Body Scan',
    mp3Filename: '27_Mini_Body_Scan.mp3',
    audioUrl: 'https://0yrs6ceohq.ufs.sh/f/TQXmWDkNFrzPeL5qWAyaBVTGMq91vwQF7huSyoLzYJ2ZHRa8',
    uploadThingFileKey: 'TQXmWDkNFrzPeL5qWAyaBVTGMq91vwQF7huSyoLzYJ2ZHRa8',
    captionsPath: '/meditations/captions/27_Mini_Body_Scan.srt',
    transcriptPath: '/meditations/transcripts/27_Mini_Body_Scan.txt',
    karaokePath: '/meditations/karaoke/27_Mini_Body_Scan.json',
    expectedDuration: '2 min',
    appArea: 'micro-learning'
  }
];

export const guidedPracticeMediaByPracticeId = Object.fromEntries(
  guidedPracticeMediaMap.map((item) => [item.practiceId, item])
);

export const guidedPracticeMediaByFilename = Object.fromEntries(
  guidedPracticeMediaMap.map((item) => [item.mp3Filename, item])
);

export function getGuidedPracticeMedia(practiceId) {
  return guidedPracticeMediaByPracticeId[practiceId] || null;
}

export function getGuidedPracticeMediaBySection(section) {
  return guidedPracticeMediaMap.filter((item) => item.section === section);
}
